### PR TITLE
Update Make & Name 4 ships

### PR DESCRIPTION
**Pull request by AlessandrielH**
added iostream
added board.h

### CODE REVIEW

**Review by jgminor7 — APPROVED** [review]
thanks!

**Review by joyminor — COMMENTED** [review]
this one has been updated in a separate pull request

**Comment by AlessandrielH** [comment]
> this one has been updated in a separate pull request

The files won't merge without the approval of this request.

**Review by joyminor — APPROVED** [review]
Thank you!

**Pull request merged**
