### PR TITLE
Removed placeholder code for Ships

### PR DESCRIPTION
**Pull request by AlessandrielH**
I had code that was holding the place of where the ships would go. I removed that code.  There is pseudocode in its place now.

### CODE REVIEW

**Review by jgminor7 — COMMENTED** [review]
place- typo on lines 71 & 94. Thanks for the update!

**Comment by AlessandrielH** [comment]
> place- typo on lines 71 & 94. Thanks for the update!

Those are deleted lines of code in red.

**Review by joyminor — APPROVED** [review]
ok

**Review by jgminor7 — APPROVED** [review]

**Review by joyminor — APPROVED** [review]
ok

**Pull request merged**
